# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - exappaccessab3001

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'exappaccessab3001'
          slot-name: 'Production'
          publish-profile: 'letewebapp23.scm.azurewebsites.net:443" userName="$todeletewebapp23" userPWD="BBtTXwF5sBNQ8ypD5w8CP7vYNsp2DzCCzYwG7gmqhpxlm0yJcCDAnZirGCov" destinationAppUrl="https://todeletewebapp23.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData><publishData><publishProfile profileName="todeletewebapp23 - Web Deploy" publishMethod="MSDeploy" publishUrl="todeletewebapp23.scm.azurewebsites.net:443" msdeploySite="todeletewebapp23" userName="$todeletewebapp23" userPWD="BBtTXwF5sBNQ8ypD5w8CP7vYNsp2DzCCzYwG7gmqhpxlm0yJcCDAnZirGCov" destinationAppUrl="https://todeletewebapp23.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="todeletewebapp23 - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-dm1-193.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="todeletewebapp23\$todeletewebapp23" userPWD="BBtTXwF5sBNQ8ypD5w8CP7vYNsp2DzCCzYwG7gmqhpxlm0yJcCDAnZirGCov" destinationAppUrl="https://todeletewebapp23.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="todeletewebapp23 - Zip Deploy" publishMethod="ZipDeploy" publishUrl="tode'
          package: .
